#
# Module manifest for module 'FlexTools'
#
# Generated by: HERNIS
#
# Generated on: 9/22/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FlexTools.psm1'

# Version number of this module.
ModuleVersion = '1.5'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-abcd-123456789012'

# Author of this module
Author = 'HERNIS'

# Company or vendor of this module
CompanyName = 'HERNIS'

# Copyright statement for this module
Copyright = '(c) HERNIS. All rights reserved.'

# Description of the functionality provided by this module
Description = 'HERNIS FLEX Tools PowerShell Module - Provides management functions for HERNIS FLEX Watchdog and modules'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('XmlWatchdogConfiguration.psm1', 'RegistryConfiguration.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Stop-FlexWatchdog',
    'Start-FlexWatchdog', 
    'Start-FlexModule',
    'Stop-FlexModule',
    'Get-FlexWatchdog',
    'Get-FlexModuleByName',
    'Get-FlexModuleList',
    'Get-FlexWatchdogRunning',
    'Set-FlexModuleStartup',
    'Get-FlexSystemVersion',
    'Get-FlexToolsVersion',
    'Set-FlexModuleDebugMode',
    'Test-WindowsSnmp',
    'Test-LsiRaidSnmp',
    'Get-LsiRaidInfoFromSnmp',
    'Get-TimeInGC'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('HERNIS', 'FLEX', 'Watchdog', 'Management', 'Monitoring', 'SNMP')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.5 (23/09/2025)
- Added Get-FlexSystemVersion function to detect HERNIS FLEX system version
- Supports both task-based systems (pre-6.6) and service-based systems (6.6+)  
- Automatically locates FLEX executable and extracts file version information

Version 1.4 (20/09/2025)
- Added Install-FlexTools.ps1 installation script with version checking
- Installation script prevents downgrades without user confirmation

Version 1.3 (12/12/2022)
- Support for enabling module crash debugging modes (Set-FlexModuleDebugMode)
- Support for checking script version (Get-FlexToolsVersion)
- Fixed issue in RAID SNMP "PD Pred. Fail Cnt" was reported incorrectly (Get-LsiRaidInfoFromSnmp)

Version 1.2 (02/05/2022)
- Support for checking if the Windows SNMP service is responding (Test-WindowsSnmp)
- Support for checking if the LSI RAID SNMP extension agent is responding (Test-LsiRaidSnmp)
- Support for info from the LSI RAID SNMP extension agent (Get-LsiRaidInfoFromSnmp)

Version 1.1 (27/04/2022)
- Support for setting startup mode (Set-FlexModuleStartup)

Version 1.0 (19/04/2022)
- Initial release with core Watchdog management functions
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}