#
# Module manifest for module 'XmlWatchdogConfiguration'
#
# Generated by: HERNIS
#
# Generated on: 9/22/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'XmlWatchdogConfiguration.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'b2c3d4e5-f6g7-8901-bcde-234567890123'

# Author of this module
Author = 'HERNIS'

# Company or vendor of this module
CompanyName = 'HERNIS'

# Copyright statement for this module
Copyright = '(c) HERNIS. All rights reserved.'

# Description of the functionality provided by this module
Description = 'XML Watchdog Configuration management for HERNIS FLEX'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = @()

}